clean: true
author: Arnaud Schloune
author_url: https://twitter.com/mmommommomo
github_url: https://github.com/arn00s/barceloneta
github_file_prefix:
module: Barceloneta
min_acl: internal
exclude: [
	Barceloneta/AppDelegate.swift,
	Barceloneta/ViewController.swift
]
hide_documentation_coverage: false
